name: Build and push to nuget
on:
  release: 
    types: [created]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
      - name: determine version string
        id: parse-version
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: "refs/tags/(.*)"
          string: ${{github.ref}}
          replace-with: "$1"      
      - name: dotnet pack
        run: dotnet pack --no-build --configuration Release -p:PackageVersion=${{ steps.parse-version.outputs.replaced }} --output .
      - name: push to nuget
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_APIKEY}}