name: Build and push to nuget
on:
  push:
    branches: [main]
  release: 
    types: [created]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
      - name: dotnet pack
        run: dotnet pack --no-build --configuration Release -p:PackageVersion=${{ env.GITHUB_REF }} --output .
      # - name: push to nuget
      #   run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_APIKEY}}